include:
  - component: $CI_SERVER_FQDN/home-lab/automations/docker-compose-service-deployment@v2.0.4
    inputs:
      vm-hostname: nas.srv.xbhl.intranet
      vm-ssh-username: $SSH_USER
      vm-ssh-private-key: $SSH_PRIVATE_KEY
      service-name: plex
      container-name: plex
      container-location: /share/Container/services/plex
      cloudflare-dns-entry-name: plex.intranet.xbhl.online
      cloudflare-zone-id: $CLOUDFLARE_ZONE_ID
      cloudflare-dns-api-token: $CLOUDFLARE_DNS_API_TOKEN
      container-healthcheck-delay: 300
      delete-existing-container-files: true

setup:generate-build-artifacts:
  script:
    - cp src/.env $BUILD_ARTIFACTS_DIR
    - sed -i "s|^PLEX_CLAIM=.*|PLEX_CLAIM=${PLEX_CLAIM}|" $BUILD_ARTIFACTS_DIR/.env
    - sed -i "s|^PLEX_DOMAIN=.*|PLEX_DOMAIN=${SERVICE_HOSTNAME}|" $BUILD_ARTIFACTS_DIR/.env

test:plex:docker-compose:
  script:
    - echo "🔵 Skipping docker-compose test due to lack of NVIDIA GPU in runner environment"
